"""
file containing solely hard coded parameters
"""
 
LEFTCAMERA = "2BA200003745"
RIGHTCAMERA = "2BA200003744"
RGBCAMERA = "2BA200004266"
 
 
WIDTH = 1280
HEIGHT = 800
 
IMAGE_RESOLUTION = (1536,2048)
 
CHESS_SHAPE = (8,11)
CHESS_BLOCK_SIZE = 19.1
 
SQUARES_X = 11
SQUARES_Y = 8
SQUARES_LENGTH = 19.4
MARKER_LENGTH = 14.7
 
WORKING_DIRECTORY = r"."
 
PROJECTOR_DIRECTORY = WORKING_DIRECTORY + r"\static\0_projection_pattern/"
CALIBRATION_DATA_DIRECTORY = WORKING_DIRECTORY + r"\static\1_calibration_data/"
INTRINSIC_CALIBRATION_DATA_DIRECTORY = WORKING_DIRECTORY + r"\static\1_calibration_data\intrinsic/"
TURNTABLE_CALIBRATION_DATA_DIRECTORY = WORKING_DIRECTORY + r"\static\1_calibration_data\turntable/"
OBJECT_DATA_DIRECTORY = WORKING_DIRECTORY + r"\static\2_object_data/"